### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by belauzas** [simonasablinaite/05-coming-soon-clock#3]
These is some white-space around the background and main photo doesn't cover all the screen

**Comment by abitsalihu** [comment]
Hey, I would like to help with this issue, by making the background cover the whole website. :)

**Comment by simonasablinaite** [comment]
Hi,
Thanks for your nice intentions, but now everything is OK.

**Comment by belauzas** [comment]
Issue is not solved yet, image doesn't cover all the screen on a big monitor
